version = 3.5.8
runner.dialect = scala213

fileOverride {
  "glob:**/scala-2*/**" {
    runner.dialect = scala213

    maxColumn = 100
    assumeStandardLibraryStripMargin = false
    align {
      stripMargin = true
    }
  }
}

fileOverride {
  "glob:**/scala-3*/**" {
    runner.dialect = scala3

    maxColumn = 100
    assumeStandardLibraryStripMargin = false
    align {
      stripMargin = true
    }
  }
}